kind: Deployment
apiVersion: apps/v1
metadata:
  name: management-api-discovery-noname-collector
  namespace: {{ .Values.discovery.namespace }}
  labels:
    app.kubernetes.io/instance: management
    app.kubernetes.io/managed-by: ibm-apiconnect
    app.kubernetes.io/name: api-discovery-noname-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: management
      app.kubernetes.io/managed-by: ibm-apiconnect
      app.kubernetes.io/name: api-discovery-noname-collector
  template:
    metadata:
      name: management-api-discovery-noname-collector
      labels:
        app.kubernetes.io/instance: management
        app.kubernetes.io/managed-by: ibm-apiconnect
        app.kubernetes.io/name: api-discovery-noname-collector
    spec:
      restartPolicy: Always
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - s390x
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsNonRoot: true
        supplementalGroups:
          - 1000
      containers:
        - resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 20m
              memory: 128Mi
          name: api-discovery-noname-collector
          env:
            - name: PROVIDER_ORG
              value: "{{ .Values.discovery.provider_org }}"
            - name: DISCOVERY_SERVER_BASE_URI
              value: "https://{{ .Values.discovery.platform_api_prefix }}.{{ .Values.discovery.apic_host_domain }}"
            - name: DEBUG
              value: "noname-discovery-client, noname-discovery-client"
            - name: LOG_LEVEL
              value: "{{ .Values.logging.log_level }}"
            - name: DATASOURCE_NAME
              value: "{{ .Values.discovery.datasource_name }}"
            - name: NONAME_HOST
              value: "https://{{ .Values.noname.host_name }}"
            - name: CLIENT_ID
              value: "{{ .Values.noname.client_id }}"
          volumeMounts:
            - mountPath: /etc/velox/credentials/client
              name: noname-client-secret
              readOnly: true
            - mountPath: /etc/velox/credentials/org
              name: noname-porg-secret
              readOnly: true
          securityContext:
            capabilities:
              drop:
                - ALL
            privileged: false
            runAsNonRoot: true
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          imagePullPolicy: Always
          image: {{ .Values.images.api_discovery_noname_collector }}
      dnsPolicy: ClusterFirst
      volumes:
      - name: noname-client-secret
        secret:
          defaultMode: 420
          secretName: noname-client-secret
      - name: noname-porg-secret
        secret:
          defaultMode: 420
          secretName: noname-porg-secret
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
