---
apiVersion: v1
data:
  apikey: {{ .Values.discovery.api_key | b64enc }}
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: management
    app.kubernetes.io/managed-by: ibm-apiconnect
    app.kubernetes.io/name: api-discovery-noname-collector
  name: noname-porg-secret
  namespace: {{ .Values.discovery.namespace }}