---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: management
    app.kubernetes.io/managed-by: ibm-apiconnect
    app.kubernetes.io/name: api-discovery-noname-collector
  name: management-api-discovery-noname-collector
  namespace: {{ .Values.discovery.namespace }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-nnlp
    port: 5557
    protocol: TCP
    targetPort: 5557
  - name: grpc-nnlp
    port: 5556
    protocol: TCP
    targetPort: 5556
  selector:
    app.kubernetes.io/instance: management
    app.kubernetes.io/managed-by: ibm-apiconnect
    app.kubernetes.io/name: api-discovery-noname-collector
  sessionAffinity: None
  type: ClusterIP

